### ISSUE TITLE
Deleting hash prevents newly generated one to show up

### ISSUE THREAD

**Issue by slacki** [uberswe/bcrypt_fun#4]
If you delete the hash from the right textarea, you won't be able to generate a new one. See photo.

![image](https://user-images.githubusercontent.com/3284061/55867246-692ddc00-5b82-11e9-9566-0b41da9ea2fd.png)

**Comment by uberswe** [comment]
@Slacki Refreshing the page should solve this for you temporarily while you wait on a fix

**Comment by uberswe** [comment]
@Slacki this has been fixed, you will need to do a hard reload to refresh main.js
